MODULE NS_S0;
(* generated by gen-secure, do not edit *)
(* Secure module: S0 *)
(* NSC base address: 00C0FE000H *)
IMPORT SYSTEM;

PROCEDURE ToggleLED*(led: SET);
BEGIN
  SYSTEM.EMITH(0B002H); (* add sp,#8, fix stack *)
  SYSTEM.EMIT(0F8DFB004H); (* ldr.w r11,[pc,#4] *)
  SYSTEM.EMITH(04758H); (* bx r11 *)
  SYSTEM.ALIGN; (* word alignment *)
  SYSTEM.DATA(00C0FE001H); (* nsc target address *)
END ToggleLED;

END NS_S0.
