MODULE NS_S0;
(* generated by gen-secure, do not edit *)
(* Secure module: S0 *)
(* NSC base address: 00C0FE000H *)
IMPORT SYSTEM, NS_DEV2;

CONST
  GPIOH_BSSR* = NS_DEV2.GPIOH_BASE + NS_DEV2.GPIO_BSRR_Offset;
  LEDred = 6;

TYPE
  TwoBits* = RECORD
  pin*: INTEGER;
  addr*: INTEGER;
  value*: INTEGER
  END;

PROCEDURE ToggleLED*(VAR led: SET);
BEGIN
  SYSTEM.EMITH(0B002H); (* add sp,#8, fix stack *)
  SYSTEM.EMIT(0F8DFB004H); (* ldr.w r11,[pc,#4] *)
  SYSTEM.EMITH(04758H); (* bx r11 *)
  SYSTEM.ALIGN; (* word alignment *)
  SYSTEM.DATA(00C0FE001H); (* nsc target address *)
END ToggleLED;

PROCEDURE SetBits*(twoBits: TwoBits);
BEGIN
  SYSTEM.EMITH(0B003H); (* add sp,#12, fix stack *)
  SYSTEM.EMIT(0F8DFB004H); (* ldr.w r11,[pc,#4] *)
  SYSTEM.EMITH(04758H); (* bx r11 *)
  SYSTEM.ALIGN; (* word alignment *)
  SYSTEM.DATA(00C0FE011H); (* nsc target address *)
END SetBits;

END NS_S0.
