"""
elfdata -- Extract debug data from Oberon listing files (library module).
--
Parses assembly listing files (.alst) generated by gen-rdb from
Astrobe compiler and linker output, and extracts:
  - Procedure metadata (params, locals, types, frame info)
  - Module structure (imports, globals, type definitions)
  - Line entries for source-level debugging
  - ARM ELF attributes
  - Constant definitions
Supports all Oberon types: scalars, arrays, records, pointers,
procedure types, and cross-module type resolution.
--
Public API:
    extract(src_dir, src_subdir, src_ext, source_lines, map_file) -> DebugData
    parse_listing(filepath, source_lines) -> ModuleSource
--
Copyright (c) 2026 Gray, gray@grayraven.org
https://oberon-rtk.org/licences/
"""
import sys
import re
import struct
import copy
from dataclasses import dataclass, field
from enum import Enum, auto
from pathlib import Path
SOURCE_EXT = '.alst'
def uleb128(value):
    result = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value != 0:
            byte |= 0x80
        result.append(byte)
        if value == 0:
            break
    return bytes(result)
def sleb128(value):
    result = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if (value == 0 and (byte & 0x40) == 0) or (value == -1 and (byte & 0x40) != 0):
            result.append(byte)
            break
        else:
            byte |= 0x80
            result.append(byte)
    return bytes(result)
DW_ATE_boolean       = 0x02
DW_ATE_float         = 0x04
DW_ATE_signed        = 0x05
DW_ATE_unsigned      = 0x07
DW_ATE_unsigned_char = 0x08
OBERON_BASE_TYPES = {
    'INTEGER':  (4, DW_ATE_signed,        'INTEGER'),
    'SET':      (4, DW_ATE_unsigned,      'SET'),
    'REAL':     (4, DW_ATE_float,         'REAL'),
    'CHAR':     (1, DW_ATE_unsigned_char, 'CHAR'),
    'BOOLEAN':  (1, DW_ATE_unsigned,      'BOOLEAN'),
    'BYTE':     (1, DW_ATE_unsigned,      'BYTE'),
    'PROCEDURE': (4, DW_ATE_unsigned,    'PROCEDURE'),
}
@dataclass
class TypeRef:
    name: str
    open_array: bool = False
    fixed_dim: int = 0
    elem: object = None
    fields: list = None
    base: str = None
    pointer_to: object = None
    is_proc_type: bool = False
    scope: str = None
@dataclass
class VarInfo:
    names: list
    typeref: TypeRef
    decl_line: int = 0
    exported_names: set = field(default_factory=set)
@dataclass
class ParamInfo:
    names: list
    typeref: TypeRef
    by_ref: bool
    decl_line: int = 0
@dataclass
class ProcSource:
    name: str
    kind: str
    int_num: object
    params: list
    local_vars: list
    result: object
    decl_line: int = 0
    local_type_defs: dict = None
@dataclass
class ModuleSource:
    name: str
    global_vars: list
    type_defs: dict
    type_sizes: dict
    procedures: list
    imports: dict = field(default_factory=dict)
    consts: dict = field(default_factory=dict)
    record_decl_lines: dict = field(default_factory=dict)
def type_size_ext(typeref, type_sizes=None):
    if typeref is None:
        return 4
    if typeref.is_proc_type:
        return 4
    if typeref.pointer_to is not None:
        return 4
    if typeref.fixed_dim > 0 and typeref.elem is not None:
        return typeref.fixed_dim * type_size_ext(typeref.elem, type_sizes)
    info = OBERON_BASE_TYPES.get(typeref.name)
    if info:
        return info[0]
    if type_sizes and typeref.name in type_sizes:
        return type_sizes[typeref.name]
    if typeref.fields is not None:
        _, total = compute_local_addresses(typeref.fields, type_sizes)
        return total
    return 4
def type_align_ext(typeref, type_sizes=None):
    if typeref is None:
        return 4
    if typeref.fixed_dim > 0 or typeref.open_array:
        return 4
    info = OBERON_BASE_TYPES.get(typeref.name)
    if info:
        return 1 if info[0] == 1 else 4
    return 4
def type_alloc_size(typeref, type_sizes=None):
    sz = type_size_ext(typeref, type_sizes)
    if typeref is not None and (typeref.fixed_dim > 0 or typeref.open_array):
        return (sz + 3) & ~3
    return sz
def _name_anonymous_records(typeref, prefix):
    if typeref.fields is None:
        return
    for var in typeref.fields:
        tr = var.typeref
        if tr is not None and tr.name == 'RECORD' and tr.fields is not None:
            field_name = var.names[0] if var.names else 'anon'
            synthetic = f'{prefix}__{field_name}'
            tr.name = synthetic
            _name_anonymous_records(tr, synthetic)
def typeref_key(typeref):
    if typeref.is_proc_type:
        return 'PROCEDURE'
    if typeref.fixed_dim > 0:
        if typeref.elem and typeref.elem.fixed_dim > 0:
            elem_key = typeref_key(typeref.elem)
            return f'ARRAY{typeref.fixed_dim}_{elem_key}'
        elem = typeref.elem.name if typeref.elem else typeref.name
        return f'ARRAY{typeref.fixed_dim}_{elem}'
    if typeref.open_array:
        elem = typeref.elem.name if typeref.elem else typeref.name
        return f'PTR_{elem}'
    if typeref.pointer_to is not None:
        target_name = typeref_key(typeref.pointer_to)
        return f'PTRTO_{target_name}'
    if typeref.scope:
        return f'{typeref.scope}::{typeref.name}'
    return typeref.name
class TK(Enum):
    IDENT      = auto()
    INTEGER    = auto()
    COMMA      = auto()
    COLON      = auto()
    SEMI       = auto()
    DOT        = auto()
    DOTDOT     = auto()
    STAR       = auto()
    EQ         = auto()
    LPAREN     = auto()
    RPAREN     = auto()
    LBRACKET   = auto()
    RBRACKET   = auto()
    EOF        = auto()
@dataclass
class Token:
    kind: TK
    text: str
    line: int
_SECTION_KEYWORDS = frozenset([
    'VAR', 'TYPE', 'CONST', 'PROCEDURE', 'BEGIN', 'END', 'MODULE', 'IMPORT',
])
_END_OPEN = frozenset([
    'BEGIN', 'IF', 'WHILE', 'FOR', 'WITH', 'CASE', 'RECORD',
])
def tokenize_alst(filepath):
    raw_lines = filepath.read_text(encoding='utf-8', errors='replace').splitlines()
    chars = []
    for line_no, line in enumerate(raw_lines, 1):
        if line.startswith('.'):
            continue
        for ch in line:
            chars.append((ch, line_no))
        chars.append(('\n', line_no))
    tokens = []
    pos = 0
    n = len(chars)
    while pos < n:
        c, line = chars[pos]
        if c in ' \t\r\n':
            pos += 1
            continue
        if c == '(' and pos + 1 < n and chars[pos + 1][0] == '*':
            pos += 2
            depth = 1
            while pos < n and depth > 0:
                c2 = chars[pos][0]
                if c2 == '(' and pos + 1 < n and chars[pos + 1][0] == '*':
                    depth += 1
                    pos += 2
                elif c2 == '*' and pos + 1 < n and chars[pos + 1][0] == ')':
                    depth -= 1
                    pos += 2
                else:
                    pos += 1
            continue
        if c == '"':
            pos += 1
            while pos < n and chars[pos][0] != '"':
                pos += 1
            if pos < n:
                pos += 1
            continue
        if c.isalpha() or c == '_':
            start = pos
            while pos < n and (chars[pos][0].isalnum() or chars[pos][0] == '_'):
                pos += 1
            text = ''.join(x[0] for x in chars[start:pos])
            tokens.append(Token(TK.IDENT, text, line))
            continue
        if c.isdigit():
            start = pos
            while pos < n and chars[pos][0].isdigit():
                pos += 1
            text = ''.join(x[0] for x in chars[start:pos])
            while pos < n and chars[pos][0].isalnum():
                pos += 1
            tokens.append(Token(TK.INTEGER, text, line))
            continue
        if c == '.' and pos + 1 < n and chars[pos + 1][0] == '.':
            tokens.append(Token(TK.DOTDOT, '..', line))
            pos += 2
            continue
        _singles = {
            ',': TK.COMMA, ':': TK.COLON, ';': TK.SEMI, '.': TK.DOT,
            '*': TK.STAR,  '=': TK.EQ,    '(': TK.LPAREN, ')': TK.RPAREN,
            '[': TK.LBRACKET, ']': TK.RBRACKET,
        }
        if c in _singles:
            tokens.append(Token(_singles[c], c, line))
            pos += 1
            continue
        pos += 1
    last_line = chars[-1][1] if chars else 1
    tokens.append(Token(TK.EOF, '', last_line))
    return tokens
class OberonParser:
    def __init__(self, tokens):
        self.tokens = tokens
        self.pos = 0
        self.const_defs = {}
    def _cur(self):
        return self.tokens[self.pos]
    def _peek(self, offset=1):
        i = min(self.pos + offset, len(self.tokens) - 1)
        return self.tokens[i]
    def _consume(self):
        tok = self.tokens[self.pos]
        if self.pos < len(self.tokens) - 1:
            self.pos += 1
        return tok
    def _is(self, text):
        t = self._cur()
        return t.kind == TK.IDENT and t.text == text
    def _at_section(self):
        t = self._cur()
        return t.kind == TK.IDENT and t.text in _SECTION_KEYWORDS
    def _skip_to_semi(self):
        while self._cur().kind not in (TK.SEMI, TK.EOF):
            self._consume()
        if self._cur().kind == TK.SEMI:
            self._consume()
    def parse_module(self):
        while self._cur().kind != TK.EOF and not self._is('MODULE'):
            self._consume()
        if self._cur().kind == TK.EOF:
            return None
        self._consume()
        name_tok = self._consume()
        module_name = name_tok.text if name_tok.kind == TK.IDENT else 'Unknown'
        if self._cur().kind == TK.SEMI:
            self._consume()
        global_vars = []
        type_defs = {}
        imports = {}
        procedures = []
        record_decl_lines = {}
        while self._cur().kind != TK.EOF:
            if self._is('IMPORT'):
                imports.update(self._parse_imports())
            elif self._is('CONST'):
                self._consume()
                self._parse_const_section()
            elif self._is('TYPE'):
                self._parse_type_decl(type_defs, record_decl_lines)
            elif self._is('VAR'):
                self._parse_var_decl(global_vars)
            elif self._is('PROCEDURE'):
                proc = self._parse_procedure()
                if proc:
                    procedures.append(proc)
            elif self._is('BEGIN') or self._is('END'):
                break
            else:
                self._consume()
        return ModuleSource(
            name=module_name,
            global_vars=global_vars,
            type_defs=type_defs,
            type_sizes={},
            procedures=procedures,
            imports=imports,
            record_decl_lines=record_decl_lines,
        )
    def _parse_imports(self):
        self._consume()
        imports = {}
        while self._cur().kind not in (TK.SEMI, TK.EOF):
            if self._cur().kind == TK.IDENT:
                alias = self._consume().text
                if (self._cur().kind == TK.COLON and
                        self._peek().kind == TK.EQ):
                    self._consume()
                    self._consume()
                    if self._cur().kind == TK.IDENT:
                        module_name = self._consume().text
                        imports[alias] = module_name
                else:
                    imports[alias] = alias
            elif self._cur().kind == TK.COMMA:
                self._consume()
            else:
                self._consume()
        if self._cur().kind == TK.SEMI:
            self._consume()
        return imports
    def _parse_const_section(self):
        while self._cur().kind != TK.EOF and not self._at_section():
            if self._cur().kind != TK.IDENT:
                self._consume()
                continue
            name = self._consume().text
            if self._cur().kind == TK.STAR:
                self._consume()
            if self._cur().kind != TK.EQ:
                while self._cur().kind not in (TK.SEMI, TK.EOF) and not self._at_section():
                    self._consume()
                if self._cur().kind == TK.SEMI:
                    self._consume()
                continue
            self._consume()
            if self._cur().kind == TK.INTEGER:
                val_text = self._consume().text
                if self._cur().kind == TK.SEMI:
                    try:
                        self.const_defs[name] = int(val_text)
                    except ValueError:
                        pass
            while self._cur().kind not in (TK.SEMI, TK.EOF) and not self._at_section():
                self._consume()
            if self._cur().kind == TK.SEMI:
                self._consume()
    def _parse_type_decl(self, type_defs, record_decl_lines=None):
        self._consume()
        while (self._cur().kind == TK.IDENT and
               self._cur().text not in _SECTION_KEYWORDS):
            name_tok = self._consume()
            name = name_tok.text
            name_line = name_tok.line
            if self._cur().kind == TK.STAR:
                self._consume()
            if self._cur().kind != TK.EQ:
                self._skip_to_semi()
                continue
            self._consume()
            typeref = self._parse_type()
            if typeref.name == 'RECORD':
                typeref = TypeRef(name=name, fields=typeref.fields, base=typeref.base)
                _name_anonymous_records(typeref, name)
                if record_decl_lines is not None:
                    record_decl_lines[name] = name_line
            elif typeref.pointer_to is not None:
                typeref = TypeRef(name=name, pointer_to=typeref.pointer_to)
            elif typeref.is_proc_type:
                typeref = TypeRef(name=name, is_proc_type=True)
            type_defs[name] = typeref
            if self._cur().kind == TK.SEMI:
                self._consume()
    def _parse_var_decl(self, var_list):
        self._consume()
        while (self._cur().kind == TK.IDENT and
               self._cur().text not in _SECTION_KEYWORDS):
            decl_line = self._cur().line
            names, exported_names = self._parse_identlist_ex()
            if not names:
                break
            if self._cur().kind != TK.COLON:
                self._skip_to_semi()
                continue
            self._consume()
            typeref = self._parse_type()
            var_list.append(VarInfo(names=names, typeref=typeref, decl_line=decl_line,
                                    exported_names=exported_names))
            if self._cur().kind == TK.SEMI:
                self._consume()
    def _parse_identlist_ex(self):
        names = []
        exported = set()
        if self._cur().kind != TK.IDENT:
            return names, exported
        n = self._consume().text
        names.append(n)
        if self._cur().kind == TK.STAR:
            self._consume()
            exported.add(n)
        while self._cur().kind == TK.COMMA:
            self._consume()
            if self._cur().kind == TK.IDENT:
                n = self._consume().text
                names.append(n)
                if self._cur().kind == TK.STAR:
                    self._consume()
                    exported.add(n)
        return names, exported
    def _parse_identlist(self):
        names, _ = self._parse_identlist_ex()
        return names
    def _parse_type(self):
        tok = self._cur()
        if tok.kind == TK.IDENT:
            if tok.text == 'ARRAY':
                return self._parse_array_type()
            if tok.text == 'RECORD':
                return self._parse_record_type()
            if tok.text == 'POINTER':
                return self._parse_pointer_type()
            if tok.text == 'PROCEDURE':
                return self._parse_procedure_type()
            name = self._consume().text
            if (self._cur().kind == TK.DOT and
                    self._peek().kind == TK.IDENT):
                self._consume()
                qual = self._consume().text
                name = f'{name}.{qual}'
            return TypeRef(name=name)
        return TypeRef(name='UNKNOWN')
    def _try_parse_dim(self):
        if self._cur().kind == TK.INTEGER:
            return int(self._consume().text)
        if (self._cur().kind == TK.IDENT and
                self._cur().text in self.const_defs):
            return self.const_defs[self._consume().text]
        return None
    def _parse_array_type(self):
        self._consume()
        if self._is('OF'):
            self._consume()
            elem = self._parse_type()
            return TypeRef(name=elem.name, open_array=True, elem=elem)
        dims = []
        dim = self._try_parse_dim()
        if dim is not None:
            dims.append(dim)
        while self._cur().kind == TK.COMMA:
            self._consume()
            dim = self._try_parse_dim()
            if dim is not None:
                dims.append(dim)
        while self._cur().kind != TK.EOF and not self._is('OF'):
            self._consume()
        if self._is('OF'):
            self._consume()
        elem = self._parse_type()
        if not dims:
            dims = [0]
        result = elem
        for d in reversed(dims):
            result = TypeRef(name=result.name, fixed_dim=d, elem=result)
        return result
    def _parse_record_type(self):
        self._consume()
        base = None
        if self._cur().kind == TK.LPAREN:
            self._consume()
            if self._cur().kind == TK.IDENT:
                base = self._consume().text
                if (self._cur().kind == TK.DOT and
                        self._peek().kind == TK.IDENT):
                    self._consume()
                    base = f'{base}.{self._consume().text}'
            if self._cur().kind == TK.RPAREN:
                self._consume()
        fields = []
        while self._cur().kind != TK.EOF:
            if self._is('END'):
                self._consume()
                break
            if self._cur().kind == TK.IDENT and self._cur().text not in _SECTION_KEYWORDS:
                decl_line = self._cur().line
                names, exported_names = self._parse_identlist_ex()
                if not names:
                    break
                if self._cur().kind != TK.COLON:
                    self._skip_to_semi()
                    continue
                self._consume()
                typeref = self._parse_type()
                fields.append(VarInfo(names=names, typeref=typeref, decl_line=decl_line,
                                      exported_names=exported_names))
                if self._cur().kind == TK.SEMI:
                    self._consume()
            else:
                self._consume()
        return TypeRef(name='RECORD', fields=fields, base=base)
    def _parse_pointer_type(self):
        self._consume()
        if self._is('TO'):
            self._consume()
        target = self._parse_type()
        return TypeRef(name=f'POINTER TO {target.name}', pointer_to=target)
    def _parse_procedure_type(self):
        self._consume()
        if self._cur().kind == TK.LPAREN:
            depth = 1
            self._consume()
            while self._cur().kind != TK.EOF and depth > 0:
                if self._cur().kind == TK.LPAREN:
                    depth += 1
                elif self._cur().kind == TK.RPAREN:
                    depth -= 1
                self._consume()
        if self._cur().kind == TK.COLON:
            self._consume()
            self._parse_type()
        return TypeRef(name='PROCEDURE', is_proc_type=True)
    def _parse_procedure(self):
        proc_line = self._cur().line
        self._consume()
        kind = 'normal'
        int_num = None
        if self._cur().kind == TK.STAR:
            kind = 'leaf'
            self._consume()
        if self._cur().kind != TK.IDENT:
            return None
        name = self._consume().text
        if self._cur().kind == TK.STAR:
            self._consume()
        if self._cur().kind == TK.LBRACKET:
            self._consume()
            if self._cur().kind == TK.INTEGER:
                int_num = int(self._consume().text)
            if self._cur().kind == TK.RBRACKET:
                self._consume()
            if kind == 'leaf':
                kind = 'leaf_interrupt'
            else:
                kind = 'interrupt'
        params = []
        if self._cur().kind == TK.LPAREN:
            params = self._parse_formal_params()
        result = None
        if self._cur().kind == TK.COLON:
            self._consume()
            result = self._parse_type()
        if self._cur().kind == TK.SEMI:
            self._consume()
        if self._is('CONST'):
            self._consume()
            self._parse_const_section()
        local_type_defs = {}
        if self._is('TYPE'):
            self._parse_type_decl(local_type_defs)
        local_vars = []
        while self._is('VAR'):
            self._parse_var_decl(local_vars)
        while self._is('PROCEDURE'):
            self._parse_procedure()
        self._skip_proc_body(name)
        return ProcSource(
            name=name,
            kind=kind,
            int_num=int_num,
            params=params,
            local_vars=local_vars,
            result=result,
            decl_line=proc_line,
            local_type_defs=local_type_defs or None,
        )
    def _parse_formal_params(self):
        self._consume()
        params = []
        while self._cur().kind not in (TK.RPAREN, TK.EOF):
            section = self._parse_fp_section()
            if section:
                params.append(section)
            if self._cur().kind == TK.SEMI:
                self._consume()
        if self._cur().kind == TK.RPAREN:
            self._consume()
        return params
    def _parse_fp_section(self):
        by_ref = False
        if self._is('VAR'):
            by_ref = True
            self._consume()
        decl_line = self._cur().line
        names = self._parse_identlist()
        if not names:
            return None
        if self._cur().kind != TK.COLON:
            return None
        self._consume()
        open_array = False
        if self._is('ARRAY'):
            self._consume()
            if self._is('OF'):
                self._consume()
                open_array = True
        if self._is('PROCEDURE'):
            typeref = self._parse_procedure_type()
            return ParamInfo(names=names, typeref=typeref, by_ref=by_ref, decl_line=decl_line)
        if self._cur().kind != TK.IDENT:
            return None
        base_name = self._consume().text
        if (self._cur().kind == TK.DOT and
                self._peek().kind == TK.IDENT):
            self._consume()
            base_name = f'{base_name}.{self._consume().text}'
        typeref = TypeRef(name=base_name, open_array=open_array)
        if open_array:
            typeref.elem = TypeRef(name=base_name)
        return ParamInfo(names=names, typeref=typeref, by_ref=by_ref, decl_line=decl_line)
    def _skip_proc_body(self, proc_name):
        tok = self._cur()
        if tok.kind == TK.IDENT and tok.text == 'BEGIN':
            self._consume()
            depth = 1
            while self._cur().kind != TK.EOF and depth > 0:
                t = self._cur()
                if t.kind == TK.IDENT:
                    if t.text in _END_OPEN:
                        depth += 1
                    elif t.text == 'END':
                        depth -= 1
                self._consume()
        elif tok.kind == TK.IDENT and tok.text == 'END':
            self._consume()
        else:
            depth = 0
            while self._cur().kind != TK.EOF:
                t = self._cur()
                if t.kind == TK.IDENT:
                    if t.text in _END_OPEN:
                        depth += 1
                    elif t.text == 'END':
                        if depth == 0:
                            self._consume()
                            if (self._cur().kind == TK.IDENT and
                                    self._cur().text == proc_name):
                                self._consume()
                                if self._cur().kind == TK.SEMI:
                                    self._consume()
                            return
                        else:
                            depth -= 1
                            if depth == 0:
                                self._consume()
                                if (self._cur().kind == TK.IDENT and
                                        self._cur().text == proc_name):
                                    self._consume()
                                    if self._cur().kind == TK.SEMI:
                                        self._consume()
                                    return
                                continue
                self._consume()
            return
        if self._cur().kind == TK.IDENT:
            self._consume()
        if self._cur().kind == TK.SEMI:
            self._consume()
_MAP_MODULE_RE = re.compile(r'^(\w+)\s+([0-9A-Fa-f]+)H\s+(\d+)')
def parse_map_file(map_path):
    result = {}
    for line in Path(map_path).read_text(errors='replace').splitlines():
        m = _MAP_MODULE_RE.match(line.strip())
        if m:
            name = m.group(1)
            addr = int(m.group(2), 16)
            size = int(m.group(3))
            if size > 0 and name not in ('End', 'Total'):
                result[name] = addr
    return result
def compute_global_addresses(var_list, data_addr_top, type_sizes=None):
    result = {}
    ptr = data_addr_top
    for var in var_list:
        sz = type_alloc_size(var.typeref, type_sizes)
        align = type_align_ext(var.typeref, type_sizes)
        for name in var.names:
            ptr = (ptr - sz) & ~(align - 1)
            result[name] = ptr
    return result
def compute_local_addresses(var_list, type_sizes=None):
    result = {}
    ptr = 0
    for var in var_list:
        sz = type_alloc_size(var.typeref, type_sizes)
        align = type_align_ext(var.typeref, type_sizes)
        for name in var.names:
            if align > 1:
                ptr = (ptr + align - 1) & ~(align - 1)
            result[name] = ptr
            ptr += sz
    ptr = (ptr + 3) & ~3
    return result, ptr
def compute_param_offsets(params, local_size, type_sizes=None):
    result = {}
    reg_idx = 0
    for param in params:
        is_open = param.typeref.open_array
        is_record = _is_record_typeref(param.typeref, type_sizes)
        reg_per = 2 if is_open else 1
        for name in param.names:
            offset = local_size + reg_idx * 4
            result[name] = (offset, param.typeref, param.by_ref, is_open, is_record)
            reg_idx += reg_per
            if is_record:
                reg_idx += 1
    return result
DW_OP_addr  = 0x03
DW_OP_deref = 0x06
DW_OP_fbreg = 0x91
def _loc_addr(address):
    expr = bytearray([DW_OP_addr])
    expr += struct.pack('<I', address)
    return bytes(expr)
def _loc_fbreg(offset):
    expr = bytearray([DW_OP_fbreg])
    expr += sleb128(offset)
    return bytes(expr)
def _loc_fbreg_deref(offset):
    expr = bytearray([DW_OP_fbreg])
    expr += sleb128(offset)
    expr.append(DW_OP_deref)
    return bytes(expr)
DW_OP_reg0  = 0x50
DW_OP_breg0 = 0x70
def _loc_reg(n):
    return bytes([DW_OP_reg0 + n])
def _loc_breg(n, offset=0):
    return bytes([DW_OP_breg0 + n]) + sleb128(offset)
def _is_array_typeref(typeref):
    return typeref is not None and typeref.fixed_dim > 0
def _is_record_typeref(typeref, type_sizes=None):
    if typeref is None:
        return False
    if typeref.is_proc_type:
        return False
    if typeref.pointer_to is not None:
        return False
    if typeref.fields is not None:
        return True
    if typeref.name in OBERON_BASE_TYPES:
        return False
    if typeref.fixed_dim > 0 or typeref.open_array:
        return False
    if type_sizes and typeref.name in type_sizes:
        return True
    return False
def compute_leaf_locations(proc_src, type_sizes=None):
    param_locs = {}
    local_locs = {}
    reg_idx = 0
    for param in proc_src.params:
        is_open = param.typeref.open_array
        is_record = _is_record_typeref(param.typeref, type_sizes)
        for name in param.names:
            if is_open:
                param_locs[name] = _loc_reg(reg_idx)
            elif param.by_ref or is_record:
                param_locs[name] = _loc_breg(reg_idx, 0)
            else:
                param_locs[name] = _loc_reg(reg_idx)
            reg_idx += 1
            if is_record:
                reg_idx += 1
        if is_open:
            reg_idx += 1
    for var in proc_src.local_vars:
        is_array = _is_array_typeref(var.typeref)
        is_record = _is_record_typeref(var.typeref, type_sizes)
        is_bool = (var.typeref.name == 'BOOLEAN' and not is_array)
        if not is_bool and not is_array and not is_record:
            for name in var.names:
                local_locs[name] = _loc_reg(reg_idx)
                reg_idx += 1
    stack_offset = 0
    for var in proc_src.local_vars:
        is_array = _is_array_typeref(var.typeref)
        is_record = _is_record_typeref(var.typeref, type_sizes)
        is_bool = (var.typeref.name == 'BOOLEAN' and not is_array)
        if is_bool:
            for name in var.names:
                local_locs[name] = _loc_fbreg(stack_offset)
                stack_offset += 1
        elif is_array or is_record:
            stack_offset = (stack_offset + 3) & ~3
            sz = type_size_ext(var.typeref, type_sizes)
            alloc_sz = (sz + 3) & ~3
            for name in var.names:
                local_locs[name] = _loc_fbreg(stack_offset)
                stack_offset += alloc_sz
    return param_locs, local_locs
ASM_LINE_RE = re.compile(
    r'^\.\s+(\d+)\s+([0-9A-Fa-f]+)\s+([0-9A-Fa-f]+)\s+(.*)'
)
PUSH_LR_RE   = re.compile(r'push(?:\.w)?\s+\{.*lr.*\}',  re.IGNORECASE)
POP_PC_RE    = re.compile(r'pop(?:\.w)?\s+\{.*pc.*\}',   re.IGNORECASE)
PUSH_REGS_RE = re.compile(r'push(?:\.w)?\s+\{([^}]+)\}', re.IGNORECASE)
SUB_SP_RE    = re.compile(r'sub\s+sp,\s*#(\d+)',          re.IGNORECASE)
DATA_ANNOTATION_RE = re.compile(r'<(Const|Global|String|Case|Type|LineNo|Pad):')
TYPE_ANNOT_RE = re.compile(r'<Type:\s*(\d+)>')
@dataclass
class ProcSymbol:
    name: str
    address: int
    size: int
@dataclass
class LineEntry:
    address: int
    line: int
@dataclass
class FrameInfo:
    address: int
    size: int
    push_size: int
    saved_regs: list
    sp_adjust: int = 0
    sub_sp_size: int = 0
@dataclass
class ModuleDebug:
    name: str
    filename: str
    procedures: list
    line_entries: list
    frame_infos: list = field(default_factory=list)
    low_pc: int = 0
    high_pc: int = 0
    module_src: object = None
@dataclass
class GlobalSymbol:
    module_name: str
    name: str
    address: int
    byte_size: int
@dataclass
class DebugData:
    modules: list
    procedures: list
    global_symbols: list = field(default_factory=list)
    debug_line: bytes = b''
    debug_info: bytes = b''
    debug_abbrev: bytes = b''
    debug_aranges: bytes = b''
    debug_pubnames: bytes = b''
    debug_str: bytes = b''
    debug_frame: bytes = b''
    arm_attributes: bytes = b''
def instr_size(hex_instr):
    return 2 if len(hex_instr) <= 5 else 4
def is_data_line(rest):
    return DATA_ANNOTATION_RE.search(rest) is not None
def parse_push_regs(mnemonic_args):
    m = PUSH_REGS_RE.search(mnemonic_args)
    if not m:
        return None
    regs = []
    for part in m.group(1).split(','):
        part = part.strip().lower()
        if part == 'lr':
            regs.append(14)
        elif part == 'sp':
            regs.append(13)
        elif part == 'pc':
            regs.append(15)
        elif part.startswith('r'):
            try:
                regs.append(int(part[1:]))
            except ValueError:
                pass
    regs.sort()
    return regs if regs else None
def parse_listing(filepath, source_lines=False):
    lines = filepath.read_text(errors='replace').splitlines()
    module_src = None
    module_name = None
    try:
        tokens = tokenize_alst(filepath)
        for ti, tok in enumerate(tokens):
            if tok.text == 'MODULE' and ti + 1 < len(tokens):
                module_name = tokens[ti + 1].text
                break
        parser = OberonParser(tokens)
        module_src = parser.parse_module()
        if module_src is not None:
            module_src.consts = dict(parser.const_defs)
    except Exception:
        pass
    if module_name is None:
        return None
    asm_lines = []
    for i, line in enumerate(lines):
        m = ASM_LINE_RE.match(line)
        if m:
            asm_lines.append((
                i + 1,
                int(m.group(1)),
                int(m.group(2), 16),
                m.group(3),
                m.group(4).strip(),
            ))
    if not asm_lines:
        return None
    addr_to_idx = {abs_addr: idx for idx, (_, _, abs_addr, _, _) in enumerate(asm_lines)}
    procedures = []
    if module_src is not None:
        for proc_src in module_src.procedures:
            decl_line = proc_src.decl_line
            if decl_line <= 0:
                continue
            for k in range(decl_line - 1, len(lines)):
                am = ASM_LINE_RE.match(lines[k])
                if am:
                    addr = int(am.group(2), 16)
                    procedures.append((proc_src.name, addr))
                    break
    init_addr = None
    last_pop_idx = None
    for j in range(len(asm_lines) - 1, -1, -1):
        if POP_PC_RE.search(asm_lines[j][4]):
            last_pop_idx = j
            break
    if last_pop_idx is not None:
        for j in range(last_pop_idx - 1, -1, -1):
            if PUSH_LR_RE.search(asm_lines[j][4]):
                init_addr = asm_lines[j][2]
                break
    proc_addrs = {addr for _, addr in procedures}
    if init_addr is not None and init_addr not in proc_addrs:
        procedures.append(('..init', init_addr))
    procedures.sort(key=lambda p: p[1])
    last_asm = asm_lines[-1]
    file_end_addr = last_asm[2] + instr_size(last_asm[3])
    proc_symbols = []
    for i, (name, addr) in enumerate(procedures):
        full_name = (f'{module_name}..init' if name == '..init'
                     else f'{module_name}.{name}')
        size = (procedures[i + 1][1] if i + 1 < len(procedures)
                else file_end_addr) - addr
        proc_symbols.append(ProcSymbol(name=full_name, address=addr, size=size))
    frame_infos = []
    for proc in proc_symbols:
        idx = addr_to_idx.get(proc.address)
        if idx is None:
            continue
        proc_end = proc.address + proc.size
        while idx < len(asm_lines) and asm_lines[idx][2] < proc_end:
            _, _, _, hex_instr, rest = asm_lines[idx]
            saved_regs = parse_push_regs(rest)
            if saved_regs is not None:
                break
            idx += 1
        else:
            continue
        if saved_regs is None:
            continue
        push_sz = instr_size(hex_instr)
        sp_adj = 0
        sub_sz = 0
        if idx + 1 < len(asm_lines):
            _, _, _, next_hex, next_rest = asm_lines[idx + 1]
            sm = SUB_SP_RE.search(next_rest)
            if sm:
                sp_adj = int(sm.group(1))
                sub_sz = instr_size(next_hex)
        frame_infos.append(FrameInfo(
            address=proc.address,
            size=proc.size,
            push_size=push_sz,
            saved_regs=saved_regs,
            sp_adjust=sp_adj,
            sub_sp_size=sub_sz,
        ))
    line_entries = []
    if source_lines:
        current_source_line = 1
        for i, line in enumerate(lines):
            if ASM_LINE_RE.match(line):
                m = ASM_LINE_RE.match(line)
                if m and not is_data_line(m.group(4).strip()):
                    abs_addr = int(m.group(2), 16)
                    line_entries.append(LineEntry(address=abs_addr, line=current_source_line))
            elif line.strip():
                current_source_line = i + 1
    else:
        for line_no, rel_off, abs_addr, hex_inst, rest in asm_lines:
            if not is_data_line(rest):
                line_entries.append(LineEntry(address=abs_addr, line=line_no))
    low_pc  = asm_lines[0][2]
    high_pc = file_end_addr
    type_sizes = {}
    if module_src is not None:
        for type_name, decl_line in module_src.record_decl_lines.items():
            record_depth = 0
            found_record = False
            for k in range(decl_line - 1, len(lines)):
                line = lines[k]
                if ASM_LINE_RE.match(line):
                    if found_record and record_depth <= 0:
                        tm = TYPE_ANNOT_RE.search(line)
                        if tm:
                            size = int(tm.group(1))
                            if size > 0:
                                type_sizes[type_name] = size
                    break
                else:
                    stripped = line.strip()
                    for _ in re.findall(r'\bRECORD\b', stripped):
                        record_depth += 1
                        found_record = True
                    for _ in re.findall(r'\bEND\b', stripped):
                        record_depth -= 1
        module_src.type_sizes = type_sizes
    return ModuleDebug(
        name=module_name,
        filename=filepath.name,
        procedures=proc_symbols,
        line_entries=line_entries,
        frame_infos=frame_infos,
        low_pc=low_pc,
        high_pc=high_pc,
        module_src=module_src,
    )
DW_TAG_compile_unit    = 0x11
DW_TAG_subprogram      = 0x2E
DW_TAG_base_type       = 0x24
DW_TAG_variable        = 0x34
DW_TAG_formal_parameter = 0x05
DW_TAG_array_type      = 0x01
DW_TAG_subrange_type   = 0x21
DW_TAG_pointer_type    = 0x0F
DW_TAG_structure_type  = 0x13
DW_TAG_member          = 0x0D
DW_CHILDREN_no  = 0x00
DW_CHILDREN_yes = 0x01
DW_AT_name       = 0x03
DW_AT_language   = 0x13
DW_AT_comp_dir   = 0x1B
DW_AT_low_pc     = 0x11
DW_AT_high_pc    = 0x12
DW_AT_stmt_list  = 0x10
DW_AT_producer   = 0x25
DW_AT_frame_base = 0x40
DW_AT_byte_size  = 0x0B
DW_AT_encoding   = 0x3E
DW_AT_type       = 0x49
DW_AT_upper_bound = 0x2F
DW_AT_lower_bound = 0x22
DW_AT_external   = 0x3F
DW_AT_decl_file  = 0x3A
DW_AT_decl_line  = 0x3B
DW_AT_linkage_name = 0x6E
DW_AT_data_member_location = 0x38
DW_AT_GNU_pubnames = 0x2134
DW_FORM_string     = 0x08
DW_FORM_strp       = 0x0E
DW_FORM_addr       = 0x01
DW_FORM_data1      = 0x0B
DW_FORM_data2      = 0x05
DW_FORM_data4      = 0x06
DW_FORM_sec_offset = 0x17
DW_FORM_exprloc    = 0x18
DW_FORM_ref4         = 0x13
DW_FORM_flag_present = 0x19
class DebugStrTable:
    def __init__(self):
        self._data = bytearray()
        self._index = {}
    def intern(self, s: str) -> int:
        if s not in self._index:
            self._index[s] = len(self._data)
            self._data += s.encode('utf-8') + b'\x00'
        return self._index[s]
    def build(self) -> bytes:
        return bytes(self._data)
DW_LANG_Mips_Assembler = 0x8001
DW_LANG_C99            = 0x000C
DW_OP_reg13  = 0x5D
DW_OP_breg13 = 0x7D
DW_LNS_copy            = 1
DW_LNS_advance_pc      = 2
DW_LNS_advance_line    = 3
DW_LNS_set_file        = 4
DW_LNS_set_column      = 5
DW_LNS_negate_stmt     = 6
DW_LNS_set_basic_block = 7
DW_LNS_const_add_pc    = 8
DW_LNS_fixed_advance_pc = 9
DW_LNS_set_prologue_end = 10
DW_LNS_set_epilogue_begin = 11
DW_LNS_set_isa         = 12
DW_LNE_end_sequence = 1
DW_LNE_set_address  = 2
DW_CFA_advance_loc  = 0x40
DW_CFA_offset       = 0x80
DW_CFA_nop          = 0x00
DW_CFA_def_cfa      = 0x0C
DW_CFA_def_cfa_offset = 0x0E
DW_CFA_advance_loc1 = 0x02
DW_CFA_advance_loc2 = 0x03
DW_CFA_advance_loc4 = 0x04
def build_debug_abbrev():
    data = bytearray()
    def _abbrev(code, tag, has_children, attrs):
        data.extend(uleb128(code))
        data.extend(uleb128(tag))
        data.append(DW_CHILDREN_yes if has_children else DW_CHILDREN_no)
        for at, form in attrs:
            data.extend(uleb128(at))
            data.extend(uleb128(form))
        data.extend(uleb128(0))
        data.extend(uleb128(0))
    _abbrev(1, DW_TAG_compile_unit, True, [
        (DW_AT_name,      DW_FORM_string),
        (DW_AT_comp_dir,  DW_FORM_string),
        (DW_AT_low_pc,    DW_FORM_addr),
        (DW_AT_high_pc,   DW_FORM_data4),
        (DW_AT_stmt_list, DW_FORM_sec_offset),
        (DW_AT_producer,  DW_FORM_string),
        (DW_AT_language,  DW_FORM_data2),
    ])
    _abbrev(2, DW_TAG_subprogram, True, [
        (DW_AT_name,       DW_FORM_string),
        (DW_AT_low_pc,     DW_FORM_addr),
        (DW_AT_high_pc,    DW_FORM_data4),
        (DW_AT_frame_base, DW_FORM_exprloc),
    ])
    _abbrev(3, DW_TAG_base_type, False, [
        (DW_AT_name,      DW_FORM_string),
        (DW_AT_encoding,  DW_FORM_data1),
        (DW_AT_byte_size, DW_FORM_data1),
    ])
    _abbrev(4, DW_TAG_variable, False, [
        (DW_AT_name,     DW_FORM_string),
        (DW_AT_type,     DW_FORM_ref4),
        (DW_AT_low_pc,   DW_FORM_exprloc),
    ])
    data = bytearray()
    def _attr(at, form):
        return (at, form)
    def emit_abbrev(code, tag, has_children, attrs):
        data.extend(uleb128(code))
        data.extend(uleb128(tag))
        data.append(DW_CHILDREN_yes if has_children else DW_CHILDREN_no)
        for at, form in attrs:
            data.extend(uleb128(at))
            data.extend(uleb128(form))
        data.extend(b'\x00\x00')
    DW_AT_location = 0x02
    emit_abbrev(1, DW_TAG_compile_unit, True, [
        _attr(DW_AT_name,          DW_FORM_strp),
        _attr(DW_AT_comp_dir,      DW_FORM_strp),
        _attr(DW_AT_low_pc,        DW_FORM_addr),
        _attr(DW_AT_high_pc,       DW_FORM_data4),
        _attr(DW_AT_stmt_list,     DW_FORM_sec_offset),
        _attr(DW_AT_producer,      DW_FORM_strp),
        _attr(DW_AT_language,      DW_FORM_data2),
        _attr(DW_AT_GNU_pubnames,  DW_FORM_flag_present),
    ])
    emit_abbrev(2, DW_TAG_subprogram, True, [
        _attr(DW_AT_name,       DW_FORM_strp),
        _attr(DW_AT_external,   DW_FORM_flag_present),
        _attr(DW_AT_low_pc,     DW_FORM_addr),
        _attr(DW_AT_high_pc,    DW_FORM_data4),
        _attr(DW_AT_frame_base, DW_FORM_exprloc),
        _attr(DW_AT_decl_file,  DW_FORM_data1),
        _attr(DW_AT_decl_line,  DW_FORM_data2),
    ])
    emit_abbrev(3, DW_TAG_base_type, False, [
        _attr(DW_AT_name,      DW_FORM_strp),
        _attr(DW_AT_encoding,  DW_FORM_data1),
        _attr(DW_AT_byte_size, DW_FORM_data1),
    ])
    emit_abbrev(4, DW_TAG_variable, False, [
        _attr(DW_AT_name,      DW_FORM_strp),
        _attr(DW_AT_type,      DW_FORM_ref4),
        _attr(DW_AT_location,  DW_FORM_exprloc),
        _attr(DW_AT_decl_file, DW_FORM_data1),
        _attr(DW_AT_decl_line, DW_FORM_data2),
    ])
    emit_abbrev(5, DW_TAG_formal_parameter, False, [
        _attr(DW_AT_name,      DW_FORM_strp),
        _attr(DW_AT_type,      DW_FORM_ref4),
        _attr(DW_AT_location,  DW_FORM_exprloc),
        _attr(DW_AT_decl_file, DW_FORM_data1),
        _attr(DW_AT_decl_line, DW_FORM_data2),
    ])
    emit_abbrev(6, DW_TAG_array_type, True, [
        _attr(DW_AT_type, DW_FORM_ref4),
    ])
    emit_abbrev(7, DW_TAG_subrange_type, False, [
        _attr(DW_AT_type,        DW_FORM_ref4),
        _attr(DW_AT_lower_bound, DW_FORM_data4),
        _attr(DW_AT_upper_bound, DW_FORM_data4),
    ])
    emit_abbrev(8, DW_TAG_pointer_type, False, [
        _attr(DW_AT_type, DW_FORM_ref4),
    ])
    emit_abbrev(9, DW_TAG_variable, False, [
        _attr(DW_AT_name,          DW_FORM_strp),
        _attr(DW_AT_external,      DW_FORM_flag_present),
        _attr(DW_AT_type,          DW_FORM_ref4),
        _attr(DW_AT_location,      DW_FORM_exprloc),
        _attr(DW_AT_decl_file,     DW_FORM_data1),
        _attr(DW_AT_decl_line,     DW_FORM_data2),
        _attr(DW_AT_linkage_name,  DW_FORM_strp),
    ])
    emit_abbrev(10, DW_TAG_array_type, True, [
        _attr(DW_AT_type,      DW_FORM_ref4),
        _attr(DW_AT_byte_size, DW_FORM_data4),
    ])
    emit_abbrev(13, DW_TAG_array_type, True, [
        _attr(DW_AT_name,      DW_FORM_strp),
        _attr(DW_AT_type,      DW_FORM_ref4),
        _attr(DW_AT_byte_size, DW_FORM_data4),
    ])
    emit_abbrev(11, DW_TAG_structure_type, True, [
        _attr(DW_AT_name,      DW_FORM_strp),
        _attr(DW_AT_byte_size, DW_FORM_data4),
    ])
    emit_abbrev(12, DW_TAG_member, False, [
        _attr(DW_AT_name,                  DW_FORM_strp),
        _attr(DW_AT_type,                  DW_FORM_ref4),
        _attr(DW_AT_data_member_location,  DW_FORM_data4),
    ])
    emit_abbrev(14, DW_TAG_pointer_type, False, [
        _attr(DW_AT_byte_size, DW_FORM_data1),
        _attr(DW_AT_type,      DW_FORM_ref4),
    ])
    data.append(0)
    return bytes(data)
def build_debug_line_program(module, src_subdir):
    if not module.line_entries:
        return b''
    dir_table = bytearray()
    dir_table += src_subdir.encode('utf-8') + b'\x00'
    dir_table += b'\x00'
    file_table = bytearray()
    file_table += module.filename.encode('utf-8') + b'\x00'
    file_table += uleb128(1)
    file_table += uleb128(0)
    file_table += uleb128(0)
    file_table += b'\x00'
    min_inst_length = 2
    max_ops_per_inst = 1
    default_is_stmt = 1
    line_base = -5
    line_range = 14
    opcode_base = 13
    std_opcode_lengths = bytes([0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1])
    header_fields = bytearray()
    header_fields.append(min_inst_length)
    header_fields.append(max_ops_per_inst)
    header_fields.append(default_is_stmt)
    header_fields.append(line_base & 0xFF)
    header_fields.append(line_range)
    header_fields.append(opcode_base)
    header_fields += std_opcode_lengths
    header_fields += dir_table
    header_fields += file_table
    header_length = len(header_fields)
    program = bytearray()
    prev_addr = 0
    prev_line = 1
    for i, entry in enumerate(module.line_entries):
        if i == 0:
            addr_bytes = struct.pack('<I', entry.address)
            program.append(0)
            program += uleb128(1 + len(addr_bytes))
            program.append(DW_LNE_set_address)
            program += addr_bytes
            if entry.line != prev_line:
                program.append(DW_LNS_advance_line)
                program += sleb128(entry.line - prev_line)
            program.append(DW_LNS_copy)
            prev_addr = entry.address
            prev_line = entry.line
        else:
            addr_delta = entry.address - prev_addr
            line_delta = entry.line - prev_line
            addr_advance = addr_delta // min_inst_length
            adjusted_opcode = (
                (line_delta - line_base) + (line_range * addr_advance) + opcode_base
            )
            if (0 <= (line_delta - line_base) < line_range and
                    opcode_base <= adjusted_opcode < 256):
                program.append(adjusted_opcode)
            else:
                if addr_delta > 0:
                    program.append(DW_LNS_advance_pc)
                    program += uleb128(addr_advance)
                if line_delta != 0:
                    program.append(DW_LNS_advance_line)
                    program += sleb128(line_delta)
                program.append(DW_LNS_copy)
            prev_addr = entry.address
            prev_line = entry.line
    program.append(0)
    program += uleb128(1)
    program.append(DW_LNE_end_sequence)
    version = 4
    content = bytearray()
    content += struct.pack('<H', version)
    content += struct.pack('<I', header_length)
    content += header_fields
    content += program
    unit = bytearray()
    unit += struct.pack('<I', len(content))
    unit += content
    return bytes(unit)
def _resolve_typeref(typeref, module_src, all_module_srcs):
    if not typeref:
        return typeref
    if typeref.is_proc_type:
        return typeref
    if typeref.pointer_to is not None:
        resolved_target = _resolve_typeref(typeref.pointer_to, module_src, all_module_srcs)
        if resolved_target is not typeref.pointer_to:
            return TypeRef(
                name=typeref.name,
                pointer_to=resolved_target,
            )
        return typeref
    if typeref.fixed_dim > 0 or typeref.open_array:
        if typeref.elem is not None:
            resolved_elem = _resolve_typeref(typeref.elem, module_src, all_module_srcs)
            if resolved_elem is not typeref.elem:
                return TypeRef(
                    name=resolved_elem.name,
                    open_array=typeref.open_array,
                    fixed_dim=typeref.fixed_dim,
                    elem=resolved_elem,
                )
        return typeref
    if '.' not in typeref.name:
        if (typeref.name not in OBERON_BASE_TYPES and
                hasattr(module_src, 'type_defs') and module_src.type_defs):
            local_resolved = module_src.type_defs.get(typeref.name)
            if local_resolved is not None and local_resolved is not typeref:
                return _resolve_typeref(local_resolved, module_src, all_module_srcs)
        return typeref
    qualifier, local_name = typeref.name.split('.', 1)
    if not hasattr(module_src, 'imports') or not module_src.imports:
        return typeref
    imported_module_name = module_src.imports.get(qualifier)
    if imported_module_name is None:
        return typeref
    imported_src = all_module_srcs.get(imported_module_name)
    if imported_src is None:
        return typeref
    resolved = imported_src.type_defs.get(local_name)
    if resolved is None:
        return typeref
    resolved = _resolve_typeref(resolved, imported_src, all_module_srcs)
    return resolved
def _resolve_record_fields(typeref, resolve_fn):
    if typeref is None or typeref.fields is None:
        return
    for var in typeref.fields:
        var.typeref = resolve_fn(var.typeref)
        _resolve_record_fields(var.typeref, resolve_fn)
def _resolve_record_base(typeref, module_src, all_module_srcs):
    if typeref is None or typeref.base is None:
        return
    if typeref.fields is None:
        typeref.fields = []
    base_name = typeref.base
    if '.' in base_name:
        qualifier, local_name = base_name.split('.', 1)
        imported_module_name = module_src.imports.get(qualifier)
        if imported_module_name is None:
            typeref.base = None
            return
        imported_src = all_module_srcs.get(imported_module_name)
        if imported_src is None:
            typeref.base = None
            return
        base_tr = imported_src.type_defs.get(local_name)
        if base_tr is None:
            typeref.base = None
            return
        _resolve_record_base(base_tr, imported_src, all_module_srcs)
    else:
        base_tr = module_src.type_defs.get(base_name)
        if base_tr is None:
            typeref.base = None
            return
        _resolve_record_base(base_tr, module_src, all_module_srcs)
    if base_tr.fields is None:
        typeref.base = None
        return
    inherited = copy.deepcopy(base_tr.fields)
    typeref.fields = inherited + typeref.fields
    typeref.base = None
def _resolve_module_typerefs(module_src, all_module_srcs):
    def resolve(tr):
        return _resolve_typeref(tr, module_src, all_module_srcs)
    for tname in list(module_src.type_defs):
        tr = module_src.type_defs[tname]
        _resolve_record_base(tr, module_src, all_module_srcs)
    for proc in module_src.procedures:
        if proc.local_type_defs:
            for tname in list(proc.local_type_defs):
                tr = proc.local_type_defs[tname]
                _resolve_record_base(tr, module_src, all_module_srcs)
    for tname in list(module_src.type_defs):
        tr = module_src.type_defs[tname]
        _resolve_record_fields(tr, resolve)
    for var in module_src.global_vars:
        var.typeref = resolve(var.typeref)
        _resolve_record_fields(var.typeref, resolve)
    for proc in module_src.procedures:
        if proc.local_type_defs:
            for tname in list(proc.local_type_defs):
                tr = proc.local_type_defs[tname]
                _resolve_record_fields(tr, resolve)
                if tr.fields is not None:
                    tr.scope = proc.name
        for param in proc.params:
            param.typeref = resolve(param.typeref)
            _resolve_record_fields(param.typeref, resolve)
        for var in proc.local_vars:
            if proc.local_type_defs and var.typeref.name in proc.local_type_defs:
                var.typeref = proc.local_type_defs[var.typeref.name]
            var.typeref = resolve(var.typeref)
            _resolve_record_fields(var.typeref, resolve)
def _collect_base_types(module_src, resolve_fn=None):
    used = set()
    visited = set()
    def add(typeref):
        if typeref is None:
            return
        tr = resolve_fn(typeref) if resolve_fn else typeref
        if id(tr) in visited:
            return
        visited.add(id(tr))
        if tr.is_proc_type:
            used.add('PROCEDURE')
            return
        if tr.name in OBERON_BASE_TYPES:
            used.add(tr.name)
        if tr.pointer_to is not None:
            add(tr.pointer_to)
            return
        if tr.elem:
            add(tr.elem)
        elif typeref.elem and typeref.elem is not tr:
            add(typeref.elem)
        if tr.fields is not None:
            for fvar in tr.fields:
                add(fvar.typeref)
    for var in module_src.global_vars:
        add(var.typeref)
    for proc in module_src.procedures:
        for param in proc.params:
            add(param.typeref)
        for var in proc.local_vars:
            add(var.typeref)
    def has_fixed_array(var_list):
        return any(v.typeref.fixed_dim > 0 for v in var_list)
    if has_fixed_array(module_src.global_vars):
        used.add('INTEGER')
    else:
        for proc in module_src.procedures:
            if has_fixed_array(proc.local_vars):
                used.add('INTEGER')
                break
    return used
def _emit_exprloc(content, loc_expr):
    content += uleb128(len(loc_expr))
    content += loc_expr
def _emit_variable_die(content, name, type_off, loc_expr, str_table, decl_line=0):
    content += uleb128(4)
    content += struct.pack('<I', str_table.intern(name))
    content += struct.pack('<I', type_off)
    _emit_exprloc(content, loc_expr)
    content.append(1)
    content += struct.pack('<H', decl_line)
def _emit_global_variable_die(content, name, type_off, loc_expr, str_table,
                              decl_line=0, linkage_name=None):
    content += uleb128(9)
    content += struct.pack('<I', str_table.intern(name))
    content += struct.pack('<I', type_off)
    _emit_exprloc(content, loc_expr)
    content.append(1)
    content += struct.pack('<H', decl_line)
    content += struct.pack('<I', str_table.intern(linkage_name or name))
def _emit_formal_parameter_die(content, name, type_off, loc_expr, str_table, decl_line=0):
    content += uleb128(5)
    content += struct.pack('<I', str_table.intern(name))
    content += struct.pack('<I', type_off)
    _emit_exprloc(content, loc_expr)
    content.append(1)
    content += struct.pack('<H', decl_line)
def build_debug_info_unit(module, abbrev_offset, stmt_list_offset, src_subdir,
                           data_addr_top=None, str_table=None, all_module_srcs=None,
                           comp_dir='.', symbol_prefix=''):
    if str_table is None:
        str_table = DebugStrTable()
    _pfx = f'{symbol_prefix}_' if symbol_prefix else ''
    content = bytearray()
    global_die_positions = []
    content += b'\x00\x00\x00\x00'
    content += struct.pack('<H', 4)
    content += struct.pack('<I', abbrev_offset)
    content.append(4)
    content += uleb128(1)
    cu_name = f'{src_subdir}/{module.filename}'
    content += struct.pack('<I', str_table.intern(cu_name))
    content += struct.pack('<I', str_table.intern(comp_dir))
    content += struct.pack('<I', module.low_pc)
    content += struct.pack('<I', module.high_pc - module.low_pc)
    content += struct.pack('<I', stmt_list_offset)
    content += struct.pack('<I', str_table.intern('makedebug (Oberon RTK)'))
    content += struct.pack('<H', DW_LANG_C99)
    type_offsets = {}
    rkey = typeref_key
    module_src = module.module_src
    if module_src is not None:
        type_sizes = module_src.type_sizes
        if all_module_srcs:
            def resolve_fn(tr):
                return _resolve_typeref(tr, module_src, all_module_srcs)
            def rkey(tr):
                return typeref_key(resolve_fn(tr))
        else:
            resolve_fn = None
            rkey = typeref_key
        for tname in sorted(_collect_base_types(module_src, resolve_fn)):
            info = OBERON_BASE_TYPES.get(tname)
            if info is None:
                continue
            sz, enc, disp_name = info
            type_offsets[tname] = len(content)
            content += uleb128(3)
            content += struct.pack('<I', str_table.intern(disp_name))
            content.append(enc)
            content.append(sz)
        array_types_needed = {}
        pointer_types_needed = {}
        reg_visited = set()
        def register_typeref(typeref):
            tr = resolve_fn(typeref) if resolve_fn else typeref
            if id(tr) in reg_visited:
                return
            reg_visited.add(id(tr))
            if tr.is_proc_type:
                return
            if tr.fixed_dim > 0 or tr.open_array:
                key = typeref_key(tr)
                if key not in type_offsets and key not in array_types_needed:
                    array_types_needed[key] = tr
                if tr.elem:
                    register_typeref(tr.elem)
            if tr.pointer_to is not None:
                key = typeref_key(tr)
                if key not in type_offsets and key not in pointer_types_needed:
                    pointer_types_needed[key] = tr
            if tr.fields is not None:
                for fvar in tr.fields:
                    register_typeref(fvar.typeref)
        for var in module_src.global_vars:
            register_typeref(var.typeref)
        for proc in module_src.procedures:
            for param in proc.params:
                register_typeref(param.typeref)
            for var in proc.local_vars:
                register_typeref(var.typeref)
        def _array_display_name(tr):
            if tr.elem and tr.elem.fixed_dim > 0:
                return f'ARRAY {tr.fixed_dim} OF {_array_display_name(tr.elem)}'
            elem = tr.elem.name if tr.elem else tr.name
            return f'ARRAY {tr.fixed_dim} OF {elem}'
        record_types_needed = {}
        rec_visited = set()
        def collect_record_types(typeref):
            if typeref is None:
                return
            if id(typeref) in rec_visited:
                return
            rec_visited.add(id(typeref))
            if typeref.pointer_to is not None:
                collect_record_types(typeref.pointer_to)
                return
            if typeref.elem is not None:
                collect_record_types(typeref.elem)
            if typeref.fields is None:
                return
            for fvar in typeref.fields:
                collect_record_types(fvar.typeref)
            key = typeref_key(typeref)
            if key not in type_offsets and key not in record_types_needed:
                record_types_needed[key] = typeref
        for var in module_src.global_vars:
            collect_record_types(var.typeref)
        for proc in module_src.procedures:
            for param in proc.params:
                collect_record_types(param.typeref)
            for var in proc.local_vars:
                collect_record_types(var.typeref)
        for tname, tref in module_src.type_defs.items():
            collect_record_types(tref)
        for rec_key, typeref in record_types_needed.items():
            byte_size = type_size_ext(typeref, type_sizes)
            type_offsets[rec_key] = len(content)
            content += uleb128(11)
            content += struct.pack('<I', str_table.intern(typeref.name))
            content += struct.pack('<I', byte_size)
            field_offsets, _ = compute_local_addresses(typeref.fields, type_sizes)
            for fvar in typeref.fields:
                for fname in fvar.names:
                    foffset = field_offsets.get(fname, 0)
                    fkey = rkey(fvar.typeref)
                    ftype_off = type_offsets.get(fkey)
                    if ftype_off is None:
                        continue
                    content += uleb128(12)
                    content += struct.pack('<I', str_table.intern(fname))
                    content += struct.pack('<I', ftype_off)
                    content += struct.pack('<I', foffset)
            content.append(0)
            for pkey, ptyperef in list(pointer_types_needed.items()):
                target = ptyperef.pointer_to
                target_key = rkey(target) if target else None
                if target_key == rec_key and target_key in type_offsets:
                    type_offsets[pkey] = len(content)
                    content += uleb128(14)
                    content.append(4)
                    content += struct.pack('<I', type_offsets[target_key])
        for key, typeref in pointer_types_needed.items():
            if key in type_offsets:
                continue
            target = typeref.pointer_to
            target_key = rkey(target) if target else None
            target_off = type_offsets.get(target_key) if target_key else None
            if target_off is None:
                continue
            type_offsets[key] = len(content)
            content += uleb128(14)
            content.append(4)
            content += struct.pack('<I', target_off)
        for key, typeref in array_types_needed.items():
            if typeref.elem:
                elem_key = typeref_key(typeref.elem)
                elem_off = type_offsets.get(elem_key)
                if elem_off is None:
                    elem_off = type_offsets.get(typeref.elem.name)
            else:
                elem_off = type_offsets.get(typeref.name)
            if elem_off is None:
                continue
            if typeref.fixed_dim > 0:
                byte_size = type_size_ext(typeref, type_sizes)
                type_offsets[key] = len(content)
                disp_name = _array_display_name(typeref)
                content += uleb128(13)
                content += struct.pack('<I', str_table.intern(disp_name))
                content += struct.pack('<I', elem_off)
                content += struct.pack('<I', byte_size)
                int_off = type_offsets.get('INTEGER', elem_off)
                content += uleb128(7)
                content += struct.pack('<I', int_off)
                content += struct.pack('<I', 0)
                content += struct.pack('<I', typeref.fixed_dim - 1)
                content.append(0)
            else:
                type_offsets[key] = len(content)
                content += uleb128(8)
                content += struct.pack('<I', elem_off)
        if data_addr_top is not None:
            global_addrs = compute_global_addresses(
                module_src.global_vars, data_addr_top, type_sizes
            )
            for var in module_src.global_vars:
                key = rkey(var.typeref)
                type_off = type_offsets.get(key)
                if type_off is None:
                    continue
                for name in var.names:
                    addr = global_addrs.get(name)
                    if addr is None:
                        continue
                    symtab_name = f'{_pfx}{module_src.name}_{name}'
                    if name in var.exported_names:
                        global_die_positions.append((symtab_name, len(content)))
                    _emit_global_variable_die(content, symtab_name, type_off, _loc_addr(addr),
                                              str_table, var.decl_line, linkage_name=symtab_name)
    frame_map = {fi.address: fi for fi in module.frame_infos}
    proc_src_map = {}
    if module_src is not None:
        proc_src_map = {p.name: p for p in module_src.procedures}
    for proc in module.procedures:
        if '.' in proc.name:
            unqualified = proc.name.split('.', 1)[1]
        else:
            unqualified = proc.name
        proc_src = proc_src_map.get(unqualified)
        fi = frame_map.get(proc.address)
        local_size = fi.sp_adjust if fi else 0
        sp_decl_line = proc_src.decl_line if proc_src is not None else 0
        content += uleb128(2)
        content += struct.pack('<I', str_table.intern(f'{_pfx}{proc.name}'))
        content += struct.pack('<I', proc.address)
        content += struct.pack('<I', proc.size)
        content += uleb128(2)
        content.append(DW_OP_breg13)
        content.append(0)
        content.append(1)
        content += struct.pack('<H', sp_decl_line)
        if proc_src is not None and module_src is not None:
            type_sizes = module_src.type_sizes
            if proc_src.kind in ('leaf', 'leaf_interrupt'):
                param_locs, local_locs = compute_leaf_locations(proc_src, type_sizes)
                for param in proc_src.params:
                    key = rkey(param.typeref)
                    type_off = type_offsets.get(key)
                    if type_off is None:
                        continue
                    for name in param.names:
                        loc = param_locs.get(name)
                        if loc is None:
                            continue
                        _emit_formal_parameter_die(content, name, type_off, loc, str_table, param.decl_line)
                for var in proc_src.local_vars:
                    key = rkey(var.typeref)
                    type_off = type_offsets.get(key)
                    if type_off is None:
                        continue
                    for name in var.names:
                        loc = local_locs.get(name)
                        if loc is None:
                            continue
                        _emit_variable_die(content, name, type_off, loc, str_table, var.decl_line)
            else:
                param_offsets = compute_param_offsets(proc_src.params, local_size, type_sizes)
                for param in proc_src.params:
                    key = rkey(param.typeref)
                    type_off = type_offsets.get(key)
                    if type_off is None:
                        continue
                    for name in param.names:
                        info = param_offsets.get(name)
                        if info is None:
                            continue
                        offset, typeref, by_ref, is_open, is_record = info
                        if is_open:
                            loc = _loc_fbreg(offset)
                        elif by_ref or is_record:
                            loc = _loc_fbreg_deref(offset)
                        else:
                            loc = _loc_fbreg(offset)
                        _emit_formal_parameter_die(content, name, type_off, loc, str_table, param.decl_line)
                local_offsets, _ = compute_local_addresses(
                    proc_src.local_vars, type_sizes
                )
                for var in proc_src.local_vars:
                    key = rkey(var.typeref)
                    type_off = type_offsets.get(key)
                    if type_off is None:
                        continue
                    for name in var.names:
                        offset = local_offsets.get(name)
                        if offset is None:
                            continue
                        _emit_variable_die(content, name, type_off, _loc_fbreg(offset), str_table, var.decl_line)
        content.append(0)
    content.append(0)
    unit_length = len(content) - 4
    struct.pack_into('<I', content, 0, unit_length)
    return bytes(content), global_die_positions
def build_debug_aranges(modules, info_offsets, module_data_tops=None):
    address_size = 4
    segment_size = 0
    data = bytearray()
    for module, info_offset in zip(modules, info_offsets):
        content = bytearray()
        content += struct.pack('<H', 2)
        content += struct.pack('<I', info_offset)
        content.append(address_size)
        content.append(segment_size)
        total_header = 4 + len(content)
        tuple_align = 2 * address_size
        pad = (tuple_align - (total_header % tuple_align)) % tuple_align
        content += b'\x00' * pad
        content += struct.pack('<I', module.low_pc)
        content += struct.pack('<I', module.high_pc - module.low_pc)
        if module_data_tops is not None and module.module_src is not None:
            data_top = module_data_tops.get(module.name)
            if data_top is not None:
                type_sizes = module.module_src.type_sizes
                addrs = compute_global_addresses(
                    module.module_src.global_vars, data_top, type_sizes)
                for var in module.module_src.global_vars:
                    sz = type_alloc_size(var.typeref, type_sizes)
                    for name in var.names:
                        addr = addrs.get(name)
                        if addr is not None:
                            content += struct.pack('<I', addr)
                            content += struct.pack('<I', sz)
        content += struct.pack('<I', 0)
        content += struct.pack('<I', 0)
        data += struct.pack('<I', len(content))
        data += content
    return bytes(data)
def build_debug_pubnames(active_modules, info_offsets, info_unit_sizes,
                          all_global_die_positions):
    data = bytearray()
    for module, info_offset, unit_size, global_dies in zip(
            active_modules, info_offsets, info_unit_sizes, all_global_die_positions):
        if not global_dies:
            continue
        content = bytearray()
        content += struct.pack('<H', 2)
        content += struct.pack('<I', info_offset)
        content += struct.pack('<I', unit_size)
        for name, die_pos_in_unit in global_dies:
            content += struct.pack('<I', die_pos_in_unit)
            content += name.encode('utf-8') + b'\x00'
        content += struct.pack('<I', 0)
        data += struct.pack('<I', len(content))
        data += content
    return bytes(data)
def _cfa_advance_loc(delta):
    data = bytearray()
    if delta <= 63:
        data.append(DW_CFA_advance_loc | delta)
    elif delta <= 255:
        data.append(DW_CFA_advance_loc1)
        data.append(delta)
    elif delta <= 65535:
        data.append(DW_CFA_advance_loc2)
        data += struct.pack('<H', delta)
    else:
        data.append(DW_CFA_advance_loc4)
        data += struct.pack('<I', delta)
    return bytes(data)
def build_debug_frame(all_frame_infos):
    if not all_frame_infos:
        return b''
    address_size = 4
    data = bytearray()
    cie_offset = 0
    cie_content = bytearray()
    cie_content += struct.pack('<I', 0xFFFFFFFF)
    cie_content.append(4)
    cie_content.append(0x00)
    cie_content.append(address_size)
    cie_content.append(0)
    cie_content += uleb128(1)
    cie_content += sleb128(-4)
    cie_content += uleb128(14)
    cie_content.append(DW_CFA_def_cfa)
    cie_content += uleb128(13)
    cie_content += uleb128(0)
    while len(cie_content) % address_size != 0:
        cie_content.append(DW_CFA_nop)
    data += struct.pack('<I', len(cie_content))
    data += cie_content
    for fi in all_frame_infos:
        fde_content = bytearray()
        fde_content += struct.pack('<I', cie_offset)
        fde_content += struct.pack('<I', fi.address)
        fde_content += struct.pack('<I', fi.size)
        num_regs = len(fi.saved_regs)
        cfa_offset_after_push = num_regs * 4
        fde_content += _cfa_advance_loc(fi.push_size)
        fde_content.append(DW_CFA_def_cfa_offset)
        fde_content += uleb128(cfa_offset_after_push)
        for k, reg in enumerate(fi.saved_regs):
            factored_offset = num_regs - k
            fde_content.append(DW_CFA_offset | reg)
            fde_content += uleb128(factored_offset)
        if fi.sp_adjust > 0:
            fde_content += _cfa_advance_loc(fi.sub_sp_size)
            fde_content.append(DW_CFA_def_cfa_offset)
            fde_content += uleb128(cfa_offset_after_push + fi.sp_adjust)
        while len(fde_content) % address_size != 0:
            fde_content.append(DW_CFA_nop)
        data += struct.pack('<I', len(fde_content))
        data += fde_content
    return bytes(data)
ARM_ATTR_TAGS = {
    'Tag_CPU_name':         (5,  'string'),
    'Tag_CPU_arch':         (6,  'int'),
    'Tag_CPU_arch_profile': (7,  'int'),
    'Tag_THUMB_ISA_use':    (9,  'int'),
    'Tag_FP_arch':          (10, 'int'),
    'Tag_ABI_VFP_args':     (28, 'int'),
    'Tag_DSP_extension':    (46, 'int'),
}
def parse_arm_attr_cfg(filepath):
    attrs = {}
    for line in filepath.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        m = re.match(r'(\w+)\s*=\s*(.*)', line)
        if not m:
            continue
        tag_name = m.group(1)
        raw_value = m.group(2).strip()
        if tag_name not in ARM_ATTR_TAGS:
            print(f'warning: unknown tag {tag_name} in {filepath}')
            continue
        _, tag_type = ARM_ATTR_TAGS[tag_name]
        if tag_type == 'string':
            attrs[tag_name] = raw_value.strip('"')
        else:
            attrs[tag_name] = int(raw_value, 16 if raw_value.startswith('0x') else 10)
    return attrs
def build_arm_attributes(attrs):
    attr_data = bytearray()
    for tag_name, (tag_num, tag_type) in sorted(ARM_ATTR_TAGS.items(),
                                                  key=lambda x: x[1][0]):
        if tag_name not in attrs:
            continue
        value = attrs[tag_name]
        attr_data += uleb128(tag_num)
        if tag_type == 'string':
            attr_data += value.encode('utf-8') + b'\x00'
        else:
            attr_data += uleb128(value)
    if not attr_data:
        return b''
    file_subsec = bytearray()
    file_subsec.append(0x01)
    file_subsec += struct.pack('<I', 4 + len(attr_data) + 1)
    file_subsec += attr_data
    vendor_name = b'aeabi\x00'
    vendor_content = vendor_name + file_subsec
    vendor = struct.pack('<I', 4 + len(vendor_content)) + vendor_content
    return bytes(b'\x41' + vendor)
def generate_dwarf(modules, src_subdir, module_data_tops=None, comp_dir='.', symbol_prefix=''):
    str_table = DebugStrTable()
    debug_abbrev = build_debug_abbrev()
    all_module_srcs = {}
    for module in modules:
        if module.module_src is not None:
            all_module_srcs[module.module_src.name] = module.module_src
    for module in modules:
        if module.module_src is not None:
            _resolve_module_typerefs(module.module_src, all_module_srcs)
    debug_line = bytearray()
    debug_info = bytearray()
    active_modules = []
    info_offsets = []
    info_unit_sizes = []
    all_global_die_positions = []
    for module in modules:
        if not module.line_entries:
            continue
        active_modules.append(module)
        stmt_list_offset = len(debug_line)
        info_offset = len(debug_info)
        info_offsets.append(info_offset)
        line_program = build_debug_line_program(module, src_subdir)
        debug_line += line_program
        data_top = None
        if module_data_tops is not None:
            data_top = module_data_tops.get(module.name)
        info_unit, global_die_positions = build_debug_info_unit(
            module, 0, stmt_list_offset, src_subdir,
            data_addr_top=data_top, str_table=str_table,
            all_module_srcs=all_module_srcs, comp_dir=comp_dir,
            symbol_prefix=symbol_prefix
        )
        debug_info += info_unit
        info_unit_sizes.append(len(info_unit))
        all_global_die_positions.append(global_die_positions)
    debug_aranges = build_debug_aranges(active_modules, info_offsets, module_data_tops)
    debug_pubnames = build_debug_pubnames(active_modules, info_offsets,
                                          info_unit_sizes, all_global_die_positions)
    debug_str = str_table.build()
    return bytes(debug_line), bytes(debug_info), debug_abbrev, debug_aranges, debug_pubnames, debug_str
def extract(src_dir, src_subdir='rdb', src_ext=None, source_lines=False,
            arm_attr_cfg=None, map_file=None, comp_dir='.', symbol_prefix=''):
    if src_ext is None:
        src_ext = SOURCE_EXT
    src_dir = Path(src_dir)
    src_files = sorted(src_dir.glob(f'*{src_ext}'))
    if not src_files:
        return DebugData(modules=[], procedures=[])
    modules = []
    all_procedures = []
    all_frame_infos = []
    for fpath in src_files:
        mod = parse_listing(fpath, source_lines=source_lines)
        if mod is not None:
            modules.append(mod)
            all_procedures.extend(mod.procedures)
            all_frame_infos.extend(mod.frame_infos)
    all_procedures.sort(key=lambda s: s.address)
    all_frame_infos.sort(key=lambda f: f.address)
    module_data_tops = None
    if map_file is not None:
        try:
            module_data_tops = parse_map_file(map_file)
        except Exception as e:
            print(f'warning: could not read map file {map_file}: {e}')
    debug_line, debug_info, debug_abbrev, debug_aranges, debug_pubnames, debug_str = generate_dwarf(
        modules, src_subdir, module_data_tops=module_data_tops, comp_dir=comp_dir,
        symbol_prefix=symbol_prefix
    )
    global_symbols = []
    if module_data_tops is not None:
        for mod in modules:
            if mod.module_src is None:
                continue
            data_top = module_data_tops.get(mod.name)
            if data_top is None:
                continue
            type_sizes = mod.module_src.type_sizes
            addrs = compute_global_addresses(
                mod.module_src.global_vars, data_top, type_sizes
            )
            for var in mod.module_src.global_vars:
                sz = type_alloc_size(var.typeref, type_sizes)
                for vname in var.names:
                    addr = addrs.get(vname)
                    if addr is not None:
                        global_symbols.append(GlobalSymbol(
                            module_name=mod.module_src.name,
                            name=vname,
                            address=addr,
                            byte_size=sz,
                        ))
    debug_frame = build_debug_frame(all_frame_infos)
    arm_attributes = b''
    if arm_attr_cfg is not None:
        attrs = parse_arm_attr_cfg(Path(arm_attr_cfg))
        if attrs:
            arm_attributes = build_arm_attributes(attrs)
    return DebugData(
        modules=modules,
        procedures=all_procedures,
        global_symbols=global_symbols,
        debug_line=debug_line,
        debug_info=debug_info,
        debug_abbrev=debug_abbrev,
        debug_aranges=debug_aranges,
        debug_pubnames=debug_pubnames,
        debug_str=debug_str,
        debug_frame=debug_frame,
        arm_attributes=arm_attributes,
    )
